---
- name: instance_template
  hosts: localhost
  gather_facts: true
  vars_files:
    - oraclecompute_vars.yaml
    - storage_vars.yaml
    
  tasks:
    - name: authenticate
      register: cookie
      oc_authenticate:
        endpoint: "{{ endpoint }}"
        user: "{{ user }}"
        password: "{{ password }}"
        
    - name: add orchestration
      oc_orchestration:
        action: "add"
        endpoint: "{{ endpoint }}"
        cookie: "{{ cookie.cookie }}"
        resourcename: "{{ resourcebase }}"
        orchestration: "{{ lookup('template', 'templates/template.json', convert_data=False) }}"

    - name: start orchestration
      oc_orchestration:
        action: "start"
        endpoint: "{{ endpoint }}"
        cookie: "{{ cookie.cookie }}"
        resourcename: "{{ resourcebase }}/{{ envorchestration }}"

    - name: monitor orchestration
      register: monitor
      oc_orchestration:
        action: "list"
        endpoint: "{{endpoint}}"
        cookie: "{{cookie.cookie}}"
        resourcename: "{{resourcebase}}/{{ envorchestration }}"
      until: monitor.list.result[0].status == "ready"
      retries: 15
      delay: 60                        