---
- name: cleanup
  hosts: localhost
  gather_facts: true
  vars_files:
    - oraclecompute_vars.yaml
    - storage_vars.yaml
  tasks:
    - name: authenticate
      register: cookie
      oc_authenticate:
        endpoint: "{{ endpoint }}"
        user: "{{ user }}"
        password: "{{ password }}"

    - name: delete storage
      oc_storagevolume:
        action: "delete"
        endpoint: "{{ endpoint }}"
        cookie: "{{ cookie.cookie }}"
        resourcename: "{{ resourcebase }}/{{ storagevolume }}"