# Deletes instance
- name: delete_instance_template
  hosts: localhost

  tasks:
    - name: Delete Server
      os_server:
           state: absent
           name:
           timeout: 500
      async: 7200
      poll: 0
      register: monitor_delete

    - name: monitor instance deletion
      async_status: jid={{ monitor_delete.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 30