# Creates a new instance and attaches to a network and passes metadata to
# the instance
- name: instance_template
  hosts: localhost

  tasks:
    - name: Create Server
      os_server:
           state: present
           name:
           image:
           key_name:
           timeout: 500
           flavor:
           auto_ip: no
           nics:
             - net-name: newnetwork
           userdata: '{"script": ""}'
     